name: CD
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: make buildWithArch
      - name: Store binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-binary
          path: ./bin/*
  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    outputs:
      uploadUrl: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: tag
        run: echo ::set-env name=versionNumber::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c 2-)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.tag.outputs.tagName }}
          release_name: Release ${{ steps.tag.outputs.tagName }}
  uploadArtifacts:
    needs: [ release ]
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.os }}-binary
      - name: Get the version
        id: binaryFilename
        run: echo ::set-output name=binaryFilename::$(make buildName)
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ steps.binaryFilename.outputs.binaryFilename }}